### ISSUE TITLE
Propose upgrading to Mattermost v4.8

### ISSUE THREAD

**Issue by lindy65** [rhdt/mattermost-openshift#7]
Hi @syamgk,

Mattermost v4.8.0 release is officially out.

You can find download links with hash numbers [here](https://pre-release.mattermost.com/core/pl/57qfbxkdrid88ci7hpasrozwda).  Changelog with notes on patch releases is available [here](https://docs.mattermost.com/administration/changelog.html). (Note: changelog has been merged and will show up a little later.)

Thanks!

**Comment by syamgk** [comment]
added the new images on https://github.com/rhdt/mattermost-openshift/commit/ab42dcd59ea6eae0d4788f4dc2e7d82db76b1682
